name: Build and Package for Testing

on:
  push:
    branches:
      - 'test-workflow' # Gatilho para pushes na branch test-workflow

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar dependências (Allegro 5)
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make liballegro5-dev liballegro-image5-dev liballegro-font5-dev liballegro-ttf5-dev liballegro-primitives5-dev liballegro-audio5-dev liballegro-acodec5-dev zip

    - name: Compilar o jogo
      run: make

    - name: Empacotar a pasta de assets
      run: zip -r assets.zip ./assets

    - name: Fazer upload dos artefatos para teste
      uses: actions/upload-artifact@v4
      with:
        name: flappy-bird-build
        path: |
          flappy.exe
          assets.zip 